spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skiandboard?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 5816

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
weather:
  cache-ttl-minutes: 30
  kma:
    service-key: 6--QdQkrT6CvkHUJK_-gjQ
  openweather:
    api-key: fada872125a9ebef9a9798f496f1e77f
    base-url: https://api.openweathermap.org/data/2.5
